#!/bin/bash
# intent-hint.sh — UserPromptSubmit hook. Prints the two or three intent-index
# entries closest to the prompt so the session can route a plain-language ask
# without reading skill bodies. Part of the conductor core (HP-9).
#
# Index: core/settings/intent-index.yaml (generated by
# core/scripts/build-intent-index.sh). A local build at
# workspace/orchestrator/intent-index.yaml wins when present, because it also
# carries personal and company skills and the cached connected apps.
#
# Matching is deliberately dumb and fast: an entry scores when one of its
# `keywords` or its name appears as a whole word in the prompt. Ties keep index
# order. Nothing is printed when nothing matches or the prompt is a slash
# command (the user already chose).
#
# Disable with HQ_INTENT_HINT=0 or HQ_DISABLED_HOOKS=intent-hint.
# Exit 0 always (additive context only).
set -uo pipefail

case "${HQ_INTENT_HINT:-1}" in 0|false|FALSE|off|OFF|no|NO) exit 0 ;; esac
disabled=",${HQ_DISABLED_HOOKS:-},"
disabled="$(printf '%s' "$disabled" | tr -d '[:space:]')"
case "$disabled" in *,intent-hint,*) exit 0 ;; esac

HQ_ROOT="${HQ_ROOT:-${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}}"
. "$HQ_ROOT/core/scripts/hook-lib.sh"

STDIN_JSON="$(cat 2>/dev/null || echo '{}')"
PROMPT="$(printf '%s' "$STDIN_JSON" | hq_json_get prompt)"
[ -n "$PROMPT" ] || exit 0
# A slash command still carries the ask in its arguments ("/startwork acme
# summarize slack"). Drop the command token so the skill does not hint itself,
# then match on what is left; a bare command stays silent.
case "$PROMPT" in /*) PROMPT="$(printf '%s' "$PROMPT" | sed -E 's/^\/[^[:space:]]+[[:space:]]*//')" ;; esac
[ -n "$PROMPT" ] || exit 0

INDEX="$HQ_ROOT/workspace/orchestrator/intent-index.yaml"
[ -f "$INDEX" ] || INDEX="$HQ_ROOT/core/settings/intent-index.yaml"
[ -f "$INDEX" ] || exit 0
MAX="${HQ_INTENT_HINT_MAX:-3}"

# Lowercase prompt, non-alphanumerics (except - and /) to spaces, padded so
# whole-word checks are a plain substring test.
WORDS=" $(printf '%s' "$PROMPT" | tr 'A-Z' 'a-z' | tr -c 'a-z0-9/\n-' ' ' | tr -s ' ') "

awk -v words="$WORDS" -v max="$MAX" '
  function unq(v) { sub(/^[ \t]+/, "", v); sub(/[ \t]+$/, "", v); if (v ~ /^".*"$/) v = substr(v, 2, length(v) - 2); return v }
  function hit(w) { return w != "" && index(words, " " w " ") > 0 }
  function flush(   n, i, k, parts) {
    if (name == "") return
    score = 0
    bare = name; sub(/^\//, "", bare)
    if (hit(bare)) score += 2
    n = split(kw, parts, ",")
    for (i = 1; i <= n; i++) { k = parts[i]; gsub(/^[ \t\[]+|[ \t\]]+$/, "", k); if (hit(k)) score += 1 }
    if (score > 0) { out[++cnt] = score "\t" name ": " use }
    name = ""; use = ""; kw = ""
  }
  /^  - name:/ { flush(); name = unq(substr($0, 10)); next }
  /^    use:/ { use = unq(substr($0, 9)); next }
  /^    keywords:/ { kw = unq(substr($0, 14)); next }
  /^[a-z]/ { flush() }
  END {
    flush()
    if (cnt == 0) exit
    # stable sort by score desc, index order for ties
    for (i = 1; i <= cnt; i++) for (j = i + 1; j <= cnt; j++) {
      split(out[i], a, "\t"); split(out[j], b, "\t")
      if (b[1] + 0 > a[1] + 0) { t = out[i]; out[i] = out[j]; out[j] = t }
    }
    print "<intent-hints>"
    lim = (cnt < max) ? cnt : max
    for (i = 1; i <= lim; i++) { split(out[i], a, "\t"); print a[2] }
    print "Pick one and proceed; read the skill body only if the one-liner is not enough. Full index: core/settings/intent-index.yaml."
    print "</intent-hints>"
  }
' "$INDEX"
exit 0
