#!/usr/bin/env bash
# generate-workers-registry.sh — regenerate core/workers/registry.yaml from
# the union of all worker.yaml files under core/workers/ and companies/*/workers/.
#
# Source of truth: each worker's worker.yaml. This file is a DERIVED index.
# Triggered automatically by .claude/hooks/master-sync.sh on every Stop and
# PostToolUse-Write event. Idempotent — writes the registry only when the
# generated content differs from the existing file (no spurious git churn).

set -euo pipefail

HQ_ROOT="${HQ_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "$HQ_ROOT"

REGISTRY_PATH="core/workers/registry.yaml"
GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

yq_get() {
  local field="$1" file="$2"
  if command -v yq >/dev/null 2>&1; then
    yq -r ".worker.${field} // \"\"" "$file" 2>/dev/null || echo ""
  else
    awk -v key="$field" '
      $0 ~ /^worker:[[:space:]]*$/ { in_w=1; next }
      in_w && /^[^[:space:]]/ { in_w=0 }
      in_w && $0 ~ "^[[:space:]]+"key":" {
        sub(/^[^:]+:[[:space:]]*/, "")
        gsub(/^["\x27]|["\x27]$/, "")
        sub(/[[:space:]]+#.*$/, "")
        print; exit
      }
    ' "$file"
  fi
}

derive_visibility() {
  local path="$1"
  case "$path" in
    core/workers/public/*) echo "public" ;;
    companies/*/workers/*) echo "private" ;;
    personal/workers/*)    echo "public" ;;
    *)                     echo "public" ;;
  esac
}

TMP_OUT="$(mktemp -t workers-registry.XXXXXX)"
TMP_ENTRIES="$(mktemp -t workers-entries.XXXXXX)"
trap 'rm -f "$TMP_OUT" "$TMP_ENTRIES"' EXIT

errors=0

while IFS= read -r yaml; do
  case "$yaml" in
    companies/_template/*) continue ;;
    # Skip any underscore-prefixed pseudo-dir (e.g. an _overrides/ snapshot
    # mirrored in via personal/workers/). These are not registry sources;
    # treating them as such produces spurious duplicate-id aborts. `find -L`
    # follows symlinked dirs, so this also covers core/workers/_overrides
    # -> personal/workers/_overrides.
    */_overrides/*|_overrides/*) continue ;;
  esac

  id=$(yq_get id "$yaml")
  type=$(yq_get type "$yaml")
  desc=$(yq_get description "$yaml")
  status=$(yq_get status "$yaml")
  company=$(yq_get company "$yaml")
  team=$(yq_get team "$yaml")

  if [[ -z "$id" || -z "$type" || -z "$desc" ]]; then
    echo "generate-workers-registry: missing required field(s) in $yaml (id=$id, type=$type, description=${desc:+set}${desc:-MISSING})" >&2
    errors=$((errors+1))
    continue
  fi

  [[ "$company" == "null" ]] && company=""
  [[ "$team" == "null" ]] && team=""
  [[ "$status" == "null" || -z "$status" ]] && status="active"

  path="$(dirname "$yaml")/"
  visibility="$(derive_visibility "$path")"

  printf '%s\x1f%s\x1f%s\x1f%s\x1f%s\x1f%s\x1f%s\x1f%s\n' \
    "$id" "$path" "$type" "$visibility" "$team" "$company" "$status" "$desc" \
    >> "$TMP_ENTRIES"
done < <(find -L core/workers companies -name worker.yaml -type f 2>/dev/null | sort)

sort -t$'\x1f' -k1,1 "$TMP_ENTRIES" -o "$TMP_ENTRIES"

# Duplicate-id guard — refuse to write a registry that would shadow workers.
dup_ids=$(cut -f1 -d$'\x1f' "$TMP_ENTRIES" | sort | uniq -d)
if [[ -n "$dup_ids" ]]; then
  echo "generate-workers-registry: duplicate worker id(s) detected — refusing to write registry:" >&2
  while IFS= read -r dup_id; do
    echo "  duplicate id: $dup_id" >&2
    grep -F "${dup_id}"$'\x1f' "$TMP_ENTRIES" | cut -f2 -d$'\x1f' | sed 's/^/    path: /' >&2
  done <<< "$dup_ids"
  echo "  Fix: change worker.id in one of the worker.yaml files above to make it unique." >&2
  exit 1
fi

{
  echo "# Workers Registry — AUTO-GENERATED by core/scripts/generate-workers-registry.sh"
  echo "# DO NOT EDIT. Source of truth: worker.yaml in each worker's directory."
  echo "# Triggered by .claude/hooks/master-sync.sh on Stop / PostToolUse-Write."
  echo "# To register a new worker: create its worker.yaml. Registry regenerates."
  echo ""
  echo "version: \"5.0\""
  echo "generated_at: \"${GENERATED_AT}\""
  echo ""
  echo "workers:"
  while IFS=$'\x1f' read -r id path type visibility team company status desc; do
    [[ -z "$id" ]] && continue
    echo "  - id: ${id}"
    echo "    path: ${path}"
    echo "    type: ${type}"
    echo "    visibility: ${visibility}"
    [[ -n "$team" ]]    && echo "    team: ${team}"
    [[ -n "$company" ]] && echo "    company: ${company}"
    echo "    status: ${status}"
    desc_esc="${desc//\"/\\\"}"
    echo "    description: \"${desc_esc}\""
  done < "$TMP_ENTRIES"
} > "$TMP_OUT"

strip_timestamp() { sed '/^generated_at:/d' "$1"; }

needs_write=1
if [[ -f "$REGISTRY_PATH" ]]; then
  if diff -q <(strip_timestamp "$REGISTRY_PATH") <(strip_timestamp "$TMP_OUT") >/dev/null 2>&1; then
    needs_write=0
  fi
fi

if [[ $needs_write -eq 1 ]]; then
  mkdir -p "$(dirname "$REGISTRY_PATH")"
  cp "$TMP_OUT" "$REGISTRY_PATH"
  echo "generate-workers-registry: wrote $REGISTRY_PATH" >&2
else
  echo "generate-workers-registry: $REGISTRY_PATH unchanged" >&2
fi

if [[ $errors -gt 0 ]]; then
  echo "generate-workers-registry: $errors worker.yaml file(s) had missing required fields — fix and re-run" >&2
  exit 1
fi

exit 0
