#!/bin/bash
# handoff-finalize.sh — collapse the mechanical tail of /handoff into one call.
#
# Folds steps 1/2/3b/4/5/7 of the handoff skill into a single subprocess so the
# model doesn't narrate each step. Writes the thread file, handoff.json,
# regenerates INDEX files, commits HQ via explicit paths, and launches qmd
# reindex fire-and-forget.
#
# Usage (all args optional, reads from stdin JSON if --from-stdin):
#   handoff-finalize.sh \
#     --title "Handoff: brief description" \
#     --summary "What was accomplished" \
#     --message "User message or autogenerated" \
#     --next-steps-json '["step 1","step 2"]' \
#     --files-touched-json '["path1","path2"]' \
#     --learnings-json '[]' \
#     --tags-json '["handoff"]' \
#     --slug "handoff-short-tag"
#
# Outputs JSON on stdout:
#   {"thread_id":"...","thread_path":"...","handoff_path":"...",
#    "hq_committed":true,"indexes_regen":true,"qmd_pid":12345}

set -euo pipefail

HQ_ROOT="${HQ_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "$HQ_ROOT"

# -------- args --------
TITLE="Handoff: session continuation"
SUMMARY=""
MESSAGE=""
NEXT_STEPS_JSON="[]"
FILES_TOUCHED_JSON="[]"
LEARNINGS_JSON="[]"
TAGS_JSON='["handoff"]'
SLUG="handoff"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --title) TITLE="$2"; shift 2 ;;
    --summary) SUMMARY="$2"; shift 2 ;;
    --message) MESSAGE="$2"; shift 2 ;;
    --next-steps-json) NEXT_STEPS_JSON="$2"; shift 2 ;;
    --files-touched-json) FILES_TOUCHED_JSON="$2"; shift 2 ;;
    --learnings-json) LEARNINGS_JSON="$2"; shift 2 ;;
    --tags-json) TAGS_JSON="$2"; shift 2 ;;
    --slug) SLUG="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

# -------- changeset path extraction / validation --------
SKIPPED_PATHS_JSON="[]"
SAFE_STAGE_PATHS=()

record_skip() {
  local path="$1"
  local reason="$2"
  SKIPPED_PATHS_JSON=$(jq -c --arg path "$path" --arg reason "$reason" \
    '. + [{path: $path, reason: $reason}]' <<<"$SKIPPED_PATHS_JSON")
}

is_sensitive_path() {
  local p="$1"
  case "$p" in
    core/settings/.gitkeep|core/settings/pure-ralph.json)
      return 1
      ;;
    .git|.git/*|.env|.env.*|*.credentials.json|*.secret.*|.hq/deploy-passwords.json|.hq/cognito-tokens.json|.claude/settings.local.json|.claude/settings.local.*|companies/*/settings/*|settings/*.json|settings/**/*.json|core/settings/*.json|core/settings/**/*.json)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

normalize_rel_path() {
  local raw="$1"
  local rel="$raw"
  if [[ "$raw" == "$HQ_ROOT/"* ]]; then
    rel="${raw#"$HQ_ROOT/"}"
  elif [[ "$raw" == /* ]]; then
    return 1
  fi
  rel="${rel#./}"
  [[ -z "$rel" ]] && return 1
  [[ "$rel" == -* || "$rel" == ".." || "$rel" == ../* || "$rel" == */../* || "$rel" == .git || "$rel" == .git/* ]] && return 1
  printf '%s\n' "$rel"
}

while IFS=$'\t' read -r raw_path deleted_flag; do
  [[ -z "${raw_path:-}" ]] && continue
  if ! rel_path=$(normalize_rel_path "$raw_path"); then
    record_skip "$raw_path" "unsafe-path"
    continue
  fi
  if is_sensitive_path "$rel_path"; then
    record_skip "$rel_path" "sensitive-path"
    continue
  fi
  if [[ ! -e "$rel_path" ]]; then
    if [[ "$deleted_flag" == "true" ]] && git ls-files --error-unmatch "$rel_path" >/dev/null 2>&1; then
      SAFE_STAGE_PATHS+=("$rel_path")
    else
      record_skip "$rel_path" "missing"
    fi
    continue
  fi
  SAFE_STAGE_PATHS+=("$rel_path")
done < <(
  printf '%s' "$FILES_TOUCHED_JSON" | jq -r '
    if type != "array" then empty else
      .[] |
      if type == "string" then
        [., "false"]
      else
        [(.path // ""), (((.deleted == true) or (.status == "deleted")) | tostring)]
      end | @tsv
    end
  ' 2>/dev/null || true
)

# -------- bg git reap (if launched by caller) --------
GIT_BG_ERRORS=""
if [[ -f /tmp/handoff-git-bg.pid ]]; then
  PID=$(cat /tmp/handoff-git-bg.pid 2>/dev/null || true)
  if [[ -n "$PID" ]]; then
    wait "$PID" 2>/dev/null || true
    if [[ -f /tmp/handoff-git-bg.log ]]; then
      GIT_BG_ERRORS=$(grep '^ERR:' /tmp/handoff-git-bg.log 2>/dev/null || true)
    fi
  fi
  rm -f /tmp/handoff-git-bg.pid
fi

# -------- thread file --------
TS=$(date -u +%Y%m%dT%H%M%SZ)
DAY=$(date +%Y%m%d)
HM=$(date +%H%M%S)
THREAD_ID="T-${DAY}-${HM}-${SLUG}"
THREAD_PATH="workspace/threads/${THREAD_ID}.json"
CHANGESET_PATH="workspace/threads/${THREAD_ID}.changeset.json"

BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || echo "DETACHED")
START_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
DIRTY="false"
[[ -n "$(git status --porcelain 2>/dev/null)" ]] && DIRTY="true"

STATUS_SUMMARY_JSON="{}"
if [[ -f core/scripts/hq-status-summary.sh ]]; then
  STATUS_SUMMARY_JSON=$(bash core/scripts/hq-status-summary.sh --session-files-json "$FILES_TOUCHED_JSON" --json 2>/dev/null || echo '{}')
fi
BASELINE_NOISE_COUNT=$(jq -r '.counts.baseline_noise // 0' <<<"$STATUS_SUMMARY_JSON" 2>/dev/null || echo 0)
SAFE_STAGE_PATHS_JSON=$(printf '%s\n' "${SAFE_STAGE_PATHS[@]:-}" | jq -R -s 'split("\n") | map(select(length > 0))')

mkdir -p workspace/threads
jq -n \
  --arg thread_id "$THREAD_ID" \
  --arg ts "$TS" \
  --arg root "$HQ_ROOT" \
  --arg cwd "$(pwd)" \
  --arg branch "$BRANCH" \
  --arg commit "$START_COMMIT" \
  --arg changeset_path "$CHANGESET_PATH" \
  --argjson dirty "$DIRTY" \
  --arg summary "$SUMMARY" \
  --arg title "$TITLE" \
  --argjson next_steps "$NEXT_STEPS_JSON" \
  --argjson files_touched "$FILES_TOUCHED_JSON" \
  --argjson learnings "$LEARNINGS_JSON" \
  --argjson tags "$TAGS_JSON" \
  '{
    thread_id: $thread_id,
    version: 1,
    type: "handoff",
    created_at: $ts,
    updated_at: $ts,
    workspace_root: $root,
    cwd: $cwd,
    git: { branch: $branch, current_commit: $commit, dirty: $dirty },
    changeset_path: $changeset_path,
    conversation_summary: $summary,
    next_steps: $next_steps,
    files_touched: $files_touched,
    learnings: $learnings,
    metadata: { title: $title, tags: $tags }
  }' > "$THREAD_PATH"

jq -n \
  --arg thread_id "$THREAD_ID" \
  --arg thread_path "$THREAD_PATH" \
  --arg ts "$TS" \
  --arg title "$TITLE" \
  --arg summary "$SUMMARY" \
  --arg branch "$BRANCH" \
  --arg started_commit "$START_COMMIT" \
  --arg finalized_commit_note "The exact handoff commit is emitted by handoff-finalize.sh as commit_after_finalize; a file cannot contain the hash of the commit that contains itself." \
  --argjson files_touched "$FILES_TOUCHED_JSON" \
  --argjson staged_paths "$SAFE_STAGE_PATHS_JSON" \
  --argjson skipped_paths "$SKIPPED_PATHS_JSON" \
  --argjson status_summary "$STATUS_SUMMARY_JSON" \
  '{
    thread_id: $thread_id,
    thread_path: $thread_path,
    created_at: $ts,
    intent: { title: $title, summary: $summary },
    git: {
      branch: $branch,
      started_commit: $started_commit,
      finalized_commit: null,
      finalized_commit_note: $finalized_commit_note
    },
    files_touched: $files_touched,
    staged_paths: $staged_paths,
    skipped_paths: $skipped_paths,
    verification: { notes: [], upstream_refs_compared: [] },
    status_summary: $status_summary
  }' > "$CHANGESET_PATH"

# -------- handoff.json pointer --------
jq -n \
  --arg ts "$TS" \
  --arg msg "$MESSAGE" \
  --arg thread_id "$THREAD_ID" \
  --arg thread_path "$THREAD_PATH" \
  --arg summary "$SUMMARY" \
  '{
    created_at: $ts,
    message: $msg,
    last_thread: $thread_id,
    thread_path: $thread_path,
    context_notes: $summary
  }' > workspace/threads/handoff.json

# -------- regen INDEX files via dedicated scripts --------
# Inline INDEX regen replaced with delegations to reusable bash scripts.
# Index regen is also callable independently (e.g. /cleanup --reindex,
# handoff-post.sh). Zero Claude context either way.
bash core/scripts/rebuild-threads-index.sh --both >/dev/null 2>&1 || true
bash core/scripts/rebuild-orchestrator-index.sh >/dev/null 2>&1 || true

# -------- INDEX.md top-level timestamp only --------
if [[ -f INDEX.md ]]; then
  # Bump 'Generated:' line in place if present, else skip
  if grep -q '^Generated:' INDEX.md; then
    tmpf=$(mktemp)
    awk -v ts="$TS" '/^Generated:/ { print "Generated: " ts; next } { print }' INDEX.md > "$tmpf"
    mv "$tmpf" INDEX.md
  fi
fi

# -------- HQ commit (explicit paths only — never git add -A) --------
HQ_COMMITTED="false"
EXPLICIT_PATHS=(
  "${SAFE_STAGE_PATHS[@]:-}"
  "workspace/threads/${THREAD_ID}.json"
  "workspace/threads/${THREAD_ID}.changeset.json"
  "workspace/threads/handoff.json"
  "workspace/threads/recent.md"
  "workspace/threads/INDEX.md"
  "workspace/orchestrator/INDEX.md"
  "INDEX.md"
)
STAGED=0
for p in "${EXPLICIT_PATHS[@]}"; do
  if [[ -e "$p" || -n "$(git status --porcelain -- "$p" 2>/dev/null)" ]]; then
    git add -- "$p" 2>/dev/null && STAGED=$((STAGED+1)) || true
  fi
done
COMMITTED_PATHS_JSON="[]"
if [[ $STAGED -gt 0 ]] && [[ -n "$(git diff --cached --name-only 2>/dev/null)" ]]; then
  COMMITTED_PATHS_JSON=$(git diff --cached --name-only | jq -R -s 'split("\n") | map(select(length > 0))')
  if git commit -m "checkpoint: handoff ${THREAD_ID}" >/dev/null 2>&1; then
    HQ_COMMITTED="true"
  fi
fi
COMMIT_AFTER=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# -------- qmd reindex fire-and-forget --------
QMD_PID=""
if command -v qmd >/dev/null 2>&1; then
  nohup bash -c 'qmd cleanup 2>/dev/null; qmd update 2>/dev/null && qmd embed 2>/dev/null' \
    > /tmp/qmd-handoff.log 2>&1 &
  QMD_PID=$!
fi

# -------- emit result --------
jq -n \
  --arg thread_id "$THREAD_ID" \
  --arg thread_path "$THREAD_PATH" \
  --arg handoff_path "workspace/threads/handoff.json" \
  --argjson hq_committed "$HQ_COMMITTED" \
  --argjson indexes_regen "true" \
  --arg qmd_pid "${QMD_PID:-}" \
  --arg git_bg_errors "$GIT_BG_ERRORS" \
  --arg changeset_path "$CHANGESET_PATH" \
  --argjson committed_paths "$COMMITTED_PATHS_JSON" \
  --argjson skipped_paths "$SKIPPED_PATHS_JSON" \
  --argjson baseline_noise_count "$BASELINE_NOISE_COUNT" \
  --arg commit_after_finalize "$COMMIT_AFTER" \
  '{
    thread_id: $thread_id,
    thread_path: $thread_path,
    changeset_path: $changeset_path,
    handoff_path: $handoff_path,
    hq_committed: $hq_committed,
    commit_after_finalize: $commit_after_finalize,
    committed_paths: $committed_paths,
    skipped_paths: $skipped_paths,
    baseline_noise_count: $baseline_noise_count,
    indexes_regen: $indexes_regen,
    qmd_pid: $qmd_pid,
    git_bg_errors: $git_bg_errors
  }'
